### PR TITLE
Catch unsupported model types in `BinaryThresholdPredictor`.

### LINKED ISSUE #486: Unsupported atomic model in `BinaryThresholdPredictor` should trigger informative error
```julia
julia> prob_predictor = RidgeRegressor()
RidgeRegressor(
  lambda = 1.0, 
  fit_intercept = true, 
  penalize_intercept = false, 
  scale_penalty_with_samples = true, 
  solver = nothing)

julia> point_predictor = BinaryThresholdPredictor(prob_predictor)
ERROR: KeyError: key Deterministic not found
Stacktrace:
 [1] getindex
   @ ./dict.jl:498 [inlined]
 [2] BinaryThresholdPredictor(args::MLJLinearModels.RidgeRegressor; wrapped_model::Nothing, 
model::Nothing, threshold::Float64)                                                        
   @ MLJModels ~/MLJ/MLJModels/src/builtins/ThresholdPredictors.jl:104
 [3] BinaryThresholdPredictor(args::MLJLinearModels.RidgeRegressor)
   @ MLJModels ~/MLJ/MLJModels/src/builtins/ThresholdPredictors.jl:89
 [4] top-level scope
   @ REPL[301]:1
```

### PR DESCRIPTION
**Pull request by ablaom**
To resolve #486.

Also adds a docstring to resolve https://github.com/alan-turing-institute/MLJ.jl/issues/973.

### CODE REVIEW

**Comment by ablaom** [comment]
@OkonSamuel Can you please review this?

File: src/builtins/ThresholdPredictors.jl [hunk 1]
```diff
@@ -67,24 +67,96 @@ const ERR_CLASSES_DETECTOR = ArgumentError(
...
+Synthesizing some unbalanced data (`y` has about ten times more 0's than 1's):
+
+```julia
+using MLJ, Random
+rng = Xoshiro(123)
+
+Xbalanced, ybalanced = make_moons(10000, xshift=0.5,noise=5.0, rng=rng)
+ybalanced = coerce(ybalanced, OrderedFactor)
+mask = map(ybalanced) do class
+    class == 0 || rand() < 0.1
```
Comment (OkonSamuel) [inline src/builtins/ThresholdPredictors.jl:105]:
```suggestion
    class == 0 || rand(rng) < 0.1
```

File: src/builtins/ThresholdPredictors.jl [hunk 2]
```diff
@@ -67,24 +67,96 @@ const ERR_CLASSES_DETECTOR = ArgumentError(
...
+)
+mach = machine(tuned_point_predictor, X, y) |> fit!
+report(mach).best_model.threshold # 0.813
+predict(mach, Xnew) # [0, 0, 0]
+```
+
+Estimating the performance of the auto-thresholding model:
+
+```julia
+e = evaluate!(mach, resampling=CV(nfolds=6), measure=[f1score, accuracy])
```
Comment (OkonSamuel) [inline src/builtins/ThresholdPredictors.jl:156]: Don't we need to create a new machine 
`mach2 = machine(report(mach).best_model, X, y)`
before evaluating it. Else the tuning process will be repeated for each fold of the evaluation process.

File: src/builtins/ThresholdPredictors.jl [hunk 3]
```diff
@@ -67,24 +67,96 @@ const ERR_CLASSES_DETECTOR = ArgumentError(
...
+tuned_point_predictor = TunedModel(
+    point_predictor,
+    tuning=RandomSearch(rng=rng),
+    resampling=CV(nfolds=6),
+    range = r,
+    measure=f1score,
+    n=30,
+)
+mach = machine(tuned_point_predictor, X, y) |> fit!
+report(mach).best_model.threshold # 0.813
```
Comment (OkonSamuel) [inline src/builtins/ThresholdPredictors.jl:149]:
```suggestion
report(mach).best_model.threshold # 0.102
```

File: src/builtins/ThresholdPredictors.jl [hunk 4]
```diff
@@ -67,24 +67,96 @@ const ERR_CLASSES_DETECTOR = ArgumentError(
...
+predict(mach, Xnew) # [0, 0, 0]
+```
+
+Estimating the performance of the auto-thresholding model:
+
+```julia
+e = evaluate!(mach, resampling=CV(nfolds=6), measure=[f1score, accuracy])
+e.measurement[1] # 0.0576
```
Comment (OkonSamuel) [inline src/builtins/ThresholdPredictors.jl:157]: This would also need to be updated.

File: src/builtins/ThresholdPredictors.jl [hunk 5]
```diff
@@ -101,8 +173,10 @@ function BinaryThresholdPredictor(args...;
         atom = model
     end
 
-    metamodel =
-        _type_given_atom[MMI.abstract_type(atom)](atom, Float64(threshold))
+    A = MMI.abstract_type(atom)
+    T = get(_type_given_atom, A, nothing)
+    isnothing(T) && throw(err_unsupported_model_type(A))
```
Comment (OkonSamuel) [inline src/builtins/ThresholdPredictors.jl:178]:
```suggestion
   T = threshold_constructor(A)
```

Then somewhere below/above add the following
```julia
for (atom, type) in type_given_atom
    @eval threshold_constructor(::Type{$atom}) = $type
end
threshold_constructor(A) = throw(err_unsupported_model_type(A))

This approach is type stable.

**Review by OkonSamuel — CHANGES_REQUESTED** [review]
Hello Anthony,

I'm sorry for the late review, I thought I had already given my review. lol
Anyways, I left some comments.

File: src/builtins/ThresholdPredictors.jl (hunk 2 above)
Comment (ablaom) [reply src/builtins/ThresholdPredictors.jl:156]: > Else the tuning process will be repeated for each fold of the evaluation process. This would mean that the threshold value used in every fold of the evaluation would be different.

Yes, this is exactly what we want! Our wrapper model is "self-tuning". Meaning, every time you fit it, it learns the best threshold. See https://mlr.mlr-org.com/articles/tutorial/nested_resampling.html .

File: src/builtins/ThresholdPredictors.jl (hunk 1 above)
Comment (ablaom) [reply src/builtins/ThresholdPredictors.jl:105]: Good spot.

File: src/builtins/ThresholdPredictors.jl (hunk 5 above)
Comment (ablaom) [reply src/builtins/ThresholdPredictors.jl]: Done.

**Comment by ablaom** [comment]
I have replaced the synthetic data with the Pima Indian diabetes data, and replaced f1score with balanced_accuracy. In this case one sees a "statistically significant" improvement in the objective function.
