### PR TITLE
fix bug in data front-end issue#440

### LINKED ISSUE #440: BinaryThresholdPredictor not working for models implementing `reformat`/`selectrows` interface
Same issue as https://github.com/JuliaAI/MLJEnsembles.jl/issues/16

### PR DESCRIPTION
**Pull request by OkonSamuel**
fixes #440 
```julia
julia> using MLJBase, MLJModels, EvoTrees

julia> threshold_classifier = BinaryThresholdPredictor(EvoTreeClassifier())
BinaryThresholdPredictor(
    model = EvoTreeClassifier(
            loss = EvoTrees.Softmax(),
            nrounds = 10,
            λ = 0.0,
            γ = 0.0,
            η = 0.1,
            max_depth = 5,
            min_weight = 1.0,
            rowsample = 1.0,
            colsample = 1.0,
            nbins = 64,
            α = 0.5,
            metric = :mlogloss,
            rng = Random.MersenneTwister(123),
            device = "cpu"),
    threshold = 0.5)

julia> X = MLJBase.table(rand(10, 10));

julia> y = categorical([2, 1, 1, 2, 1, 1, 2, 1, 1, 2], ordered=true);

julia> mach = machine(threshold_classifier, X, y) |> fit!
[ Info: Training Machine{BinaryThresholdPredictor{EvoTreeClassifier{Float64,…}},…}.
Machine{BinaryThresholdPredictor{EvoTreeClassifier{Float64,…}},…} trained 1 time; caches data
  model: BinaryThresholdPredictor{EvoTreeClassifier{Float64, EvoTrees.Softmax, Int64}}
  args:
    1:  Source @193 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @152 ⏎ `AbstractVector{OrderedFactor{2}}`


julia> predict(mach, X)
10-element CategoricalArray{Int64,1,UInt8}:
 2
 1
 1
 2
 1
 1
 2
 1
 1
 2
```

### CODE REVIEW

File: src/builtins/ThresholdPredictors.jl [hunk 1]
```diff
@@ -138,7 +138,7 @@ function MMI.fit(model::ThresholdUnion, verbosity::Int, args...)
         end
     end
     model_fitresult, model_cache, model_report = MMI.fit(
-        model.model, verbosity-1, args...
+        model.model, verbosity-1, map(unwrap_target, args)...
     )
```
Comment (ablaom) [inline src/builtins/ThresholdPredictors.jl:142]: `unwrap_target` seems like a confusing name choice - you are not just calling this on a target variable, but an all the data args. Maybe `unwrap` is better.

File: src/builtins/ThresholdPredictors.jl [hunk 2]
```diff
@@ -313,3 +317,79 @@ MMI.iteration_parameter(model::ThresholdUnion) =
...
 MMI.training_losses(thresholder::ThresholdUnion, thresholder_report) =
     MMI.training_losses(thresholder.model, thresholder_report.model_report)
+
+## Data Front-end
+"""
+    ReformattedTarget(y, levs, sci_type)
+
+Intenal Use Only.
+Wrapper containing a **model specific** target, `y`, its scientific type, 
+`sci_type`(the scientific representation of the **user supplied** target),
```
Comment (ablaom) [inline src/builtins/ThresholdPredictors.jl:327]: can we rename `sci_type` field as `scitype`?

**Review by ablaom — CHANGES_REQUESTED** [review]
Great PR with attention to detail.

Just a few minor naming suggestions.

**Comment by ablaom** [comment]
@OkonSamuel Thanks for the pull request.
